apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: tekton-kn-sample-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  params:
    - name: pathToContext
      value: "java"
    - name: pathToYamlFile
      value: "knative/helloworld-java.yaml"
    - name: imageUrl
      value: "registry.cn-hangzhou.aliyuncs.com/knative-sample/tekton-knative-helloworld-java"
    - name: imageTag
      value: "1.0"
    - name: gitRepo
      value: "https://github.com/knative-sample/tekton-helloworld-java-spring.git"
  trigger:
    type: manual
  timeout: 0h30m0s
  serviceAccount: pipeline-account
