apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: source-to-image
spec:
  inputs:
    resources:
      - name: git-source
        type: git
    params:
      - name: pathToContext
        description: The path to the build context, used by Kaniko - within the workspace
        default: .
      - name: pathToDockerFile
        description: The path to the dockerfile to build (relative to the context)
        default: Dockerfile
      - name: imageUrl
        description: Url of image repository
      - name: imageTag
        description: Tag to apply to the built image
        default: "latest"

      - name: gitRepo
        description: "git repo for user code # https://username:password@github.com/username/repository.git"
  steps:
    - name: git-clone
      image: registry.cn-hangzhou.aliyuncs.com/knative-sample/alpine-git:1.0.7
      command:
        - sh
      args:
        - -c 
        - |
          git clone '${inputs.params.gitRepo}' /workspace/home/code
          echo "git clone ${inputs.params.gitRepo} success";
          ls -al /workspace/home/code
      volumeMounts:
        - name: code-dir
          mountPath: /workspace/home/

    - name: build-and-push
      image: registry.cn-hangzhou.aliyuncs.com/knative-sample/kaniko-project-executor:v0.10.0
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.pathToDockerFile}
        - --destination=${inputs.params.imageUrl}:${inputs.params.imageTag}
        - --context=/builder/home/code/java/
      volumeMounts:
        - name: code-dir
          mountPath: /workspace/home/
      env:
      - name: DOCKER_CONFIG
        value: /builder/home/.docker
  volumes:
  - name: code-dir
    emptyDir: {}

